baseURL: https://drishti-goyal.netlify.app/
languageCode: en-us
title: Portfolio website for Kostis Christodoulou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      This is my portfolio website with all key information. Welcome to my world!
    # AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Drishti Goyal
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Great Portland St
        title: Address
    form: 
        action: "https://formspree.io/f/mbjbdenj"
        method: "POST"
        input:
            - type: "text"
              placeholder: "NAME"
            - type: "email"
              placeholder: "EMAIL"
        textarea:
              placeholder: "MESSAGE"
        input:
              type: "SEND MESSAGE"
              value: "send"
    buttonClear: Clear
    buttonSend: Send message
    formEmail: "dgoyal.mam2023@london.edu"
    email:
      - email: dgoyal.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7778608444
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Company Name
    #enable: yes
    #quicklinks:
    #   - alt: HTML5 UP
    #     text: 'Design: '
    #     url: https://www.html5up.net
    social:
  #    - icon: fa-twitter
  #      label: Twitter
  #      url: https://www.twitter.com
  #    - icon: fa-facebook
  #      label: Facebook
  #      url: https://www.facebook.com
       - icon: fa-instagram
         label: Instagram
         url: https://www.instagram.com/drishti13_/
       - icon: fa-github
         label: GitHub
         url: https://github.com/drishtigoyal13
       - icon: fa-linkedin
         label: LinkedIn
         url: https://www.linkedin.com/in/drishti-goyal/
  image: 
  name: Your name
  navigation:
    #button1:
    #  - name: Get Started
    #    url: blogs
    #button2:
    #  - name: Log In
    #    url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs/about_me
      - name: Projects
        url: blogs
    #  - name: Generic Blog
    #    url: blogs/ipsum
    #  - name: Elements
    #    url: elements.html
    menu: Menu
   # subtitle: By HTML5 Up
    title: Drishti Goyal's Portfolio Website
  tiles:
    enable: yes
    showcase:
      - image: taj_mahal.jpg
        subtitle: More about me
        title: About Me
        url: blogs/about_me
      - image: hat.png
        subtitle: More about my academic and career path
        title: Resume
        url: blogs/cv
      - image: movie.jpg
        subtitle: More about Project 1
        title: Movies Analysis
        url: blogs/movies
      - image: rent_1.jpg
        subtitle: More about Project 2
        title: Rent Analysis
        url: blogs/rent
      - image: animal.jpg
        subtitle: More about Project 3
        title: Animal Rescue Analysis
        url: blogs/animal
      #- image: pic06.jpg
      #  subtitle: Feugiat Amet Tempus
      #  title: Etiam
      #  url: blogs/ipsum
  two:
    buttonText: More about my Projects
    enable: yes
    subtitle: "An enthusiastic individual with a genuine curiosity to learn and explore new opportunities,
      \r\n    particularly in the tech sector.  \r\n    Possesses an analytical mindset with good problem-solving
      skills. Dedicated to making positive contributions wherever possible."
    title: More about me!
    url: blogs
